#Neo Bank Churn Prediction

In [1]:
# Clone the GitHub repository
!git clone https://github.com/geopan2000/Neo-Bank-Churn-Prediction.git

# Change directory to the cloned repository
%cd ChurnPrediction

Cloning into 'Neo-Bank-Churn-Prediction'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (6/6), 626.51 KiB | 1.99 MiB/s, done.
[Errno 2] No such file or directory: 'ChurnPrediction'
/content

In [2]:
# prompt: mount my drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np
import xgboost as xgb

!pip install scikit-optimize
!pip install shap
from skopt import BayesSearchCV
from skopt.space import Real, Integer

from sklearn.model_selection import KFold
from skopt import BayesSearchCV
from skopt.space import Real, Integer
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from google.colab import files

Collecting scikit-optimize
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.4.2)
Collecting pyaml>=16.9 (from scikit-optimize)
  Downloading pyaml-24.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.20.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.26.4)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.13.1)
Requirement already satisfied: scikit-learn>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (1.5.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from scikit-optimize) (24.2)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from pyaml>=16.9->scikit-optimize) (6.0.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.0->scikit-optimize) (3.5.0)
Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl (107 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.8/107.8 kB 5.2 MB/s eta 0:00:00
Downloading pyaml-24.9.0-py3-none-any.whl (24 kB)
Installing collected packages: pyaml, scikit-optimize
Successfully installed pyaml-24.9.0 scikit-optimize-0.10.2
Requirement already satisfied: shap in /usr/local/lib/python3.10/dist-packages (0.46.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from shap) (1.26.4)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from shap) (1.13.1)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from shap) (1.5.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.10/dist-packages (from shap) (4.66.6)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.10/dist-packages (from shap) (24.2)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.10/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.10/dist-packages (from shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.10/dist-packages (from shap) (3.1.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.10/dist-packages (from numba->shap) (0.43.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->shap) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->shap) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->shap) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->shap) (1.16.0)

In [6]:
train_2008 = pd.read_parquet('/content/drive/MyDrive/Neo bank churn prediction/data/train_2008.parquet')
train_2008.to_csv('train_2008.csv', index=False)
train_2008.head(50)

,Id,customer_id,interest_rate,name,country,date_of_birth,address,date,atm_transfer_in,atm_transfer_out,...,crypto_in_volume,crypto_out_volume,complaints,touchpoints,csat_scores,tenure,from_competitor,job,churn_due_to_fraud,model_predicted_fraud
0,1,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-17,0,0,...,393.145010,220.900654,0,[],"{'appointment': None, 'email': None, 'phone': ...",0,False,Amenity horticulturist,False,False
1,6,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-18,0,0,...,390.005729,221.147296,0,[],"{'appointment': None, 'email': None, 'phone': ...",1,False,Amenity horticulturist,False,False
2,16,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-19,0,0,...,393.209108,260.510535,0,[],"{'appointment': None, 'email': None, 'phone': ...",2,False,Amenity horticulturist,False,False
3,31,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-20,0,0,...,394.078294,203.214128,0,[],"{'appointment': None, 'email': None, 'phone': ...",3,False,Amenity horticulturist,False,False
4,50,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-21,0,0,...,395.174604,207.894467,0,"[whatsapp, email, email]","{'appointment': None, 'email': None, 'phone': ...",4,False,Amenity horticulturist,False,False
5,102,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-23,0,0,...,341.282736,171.205073,0,[],"{'appointment': None, 'email': None, 'phone': ...",6,False,Amenity horticulturist,False,False
6,134,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-24,0,0,...,378.111975,204.183903,0,[],"{'appointment': None, 'email': None, 'phone': ...",7,False,Amenity horticulturist,False,False
7,171,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-25,0,0,...,407.930587,197.097479,0,[],"{'appointment': None, 'email': None, 'phone': ...",8,False,Amenity horticulturist,False,False
8,211,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-26,0,0,...,377.328868,218.909579,0,[],"{'appointment': None, 'email': None, 'phone': ...",9,False,Amenity horticulturist,False,False
9,254,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-27,0,0,...,454.863033,195.062883,0,[],"{'appointment': None, 'email': None, 'phone': ...",10,False,Amenity horticulturist,False,False
10,302,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-28,0,0,...,311.800405,208.797170,0,[email],"{'appointment': None, 'email': None, 'phone': ...",11,False,Amenity horticulturist,False,False
11,353,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-29,0,0,...,341.522459,232.216551,0,[],"{'appointment': None, 'email': None, 'phone': ...",12,False,Amenity horticulturist,False,False
12,408,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-30,0,0,...,398.229624,221.566323,0,[],"{'appointment': None, 'email': None, 'phone': ...",13,False,Amenity horticulturist,False,False
13,466,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-01-31,0,0,...,361.090230,240.010361,0,[],"{'appointment': None, 'email': None, 'phone': ...",14,False,Amenity horticulturist,False,False
14,528,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-01,0,0,...,397.059196,201.438110,0,[email],"{'appointment': None, 'email': None, 'phone': ...",15,False,Amenity horticulturist,False,False
15,594,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-02,0,0,...,447.801930,185.264773,0,[],"{'appointment': None, 'email': None, 'phone': ...",16,False,Amenity horticulturist,False,False
16,665,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-03,0,0,...,408.195882,187.226472,0,[],"{'appointment': None, 'email': None, 'phone': ...",17,False,Amenity horticulturist,False,False
17,740,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-04,0,0,...,447.158723,205.275548,0,[],"{'appointment': None, 'email': None, 'phone': ...",18,False,Amenity horticulturist,False,False
18,819,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-05,0,0,...,344.377283,192.326130,0,[],"{'appointment': None, 'email': None, 'phone': ...",19,False,Amenity horticulturist,False,False
19,989,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-07,0,0,...,369.525872,235.284427,0,[],"{'appointment': None, 'email': None, 'phone': ...",21,False,Amenity horticulturist,False,False
20,1081,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-08,0,0,...,378.812204,257.995235,0,[],"{'appointment': None, 'email': None, 'phone': ...",22,False,Amenity horticulturist,False,False
21,1176,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-09,0,0,...,400.868493,193.480962,0,[],"{'appointment': None, 'email': None, 'phone': ...",23,False,Amenity horticulturist,False,False
22,1274,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-10,0,0,...,498.565486,231.596746,0,[],"{'appointment': None, 'email': None, 'phone': ...",24,False,Amenity horticulturist,False,False
23,1474,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-12,0,0,...,445.632514,196.126019,0,[],"{'appointment': None, 'email': None, 'phone': ...",26,False,Amenity horticulturist,False,False
24,1578,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-13,0,0,...,381.651831,246.830367,0,[],"{'appointment': None, 'email': None, 'phone': ...",27,False,Amenity horticulturist,False,False
25,1685,1,3.5,Yolanda Parker,Lithuania,1954-07-10,"1929 Erin Lights Suite 709\nLake Michaelburgh,...",2008-02-14,0,0,...,404.445201,223.718672,0,[],"{'appointment': None, 'email': None, 'phone': ...",28,False,Amenity horticulturist,False,False
26,2,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-17,1,0,...,45.394936,15.558941,0,[],"{'appointment': None, 'email': None, 'phone': ...",0,False,Exhibition designer,False,False
27,7,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-18,1,0,...,50.649160,13.976574,0,[],"{'appointment': None, 'email': None, 'phone': ...",1,False,Exhibition designer,False,False
28,17,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-19,1,0,...,51.245909,15.684373,0,[],"{'appointment': None, 'email': None, 'phone': ...",2,False,Exhibition designer,False,False
29,32,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-20,1,0,...,41.630729,16.196797,0,[],"{'appointment': None, 'email': None, 'phone': ...",3,False,Exhibition designer,False,False
30,51,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-21,1,0,...,47.139611,16.684812,0,[],"{'appointment': None, 'email': None, 'phone': ...",4,False,Exhibition designer,False,False
31,75,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-22,1,0,...,49.437840,13.792684,0,[],"{'appointment': None, 'email': None, 'phone': ...",5,False,Exhibition designer,False,False
32,172,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-25,1,0,...,42.358489,15.443687,0,[],"{'appointment': None, 'email': None, 'phone': ...",8,False,Exhibition designer,False,False
33,212,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-26,1,0,...,46.513935,17.222037,0,[],"{'appointment': None, 'email': None, 'phone': ...",9,False,Exhibition designer,False,False
34,255,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-27,1,0,...,51.944289,15.883376,0,[],"{'appointment': None, 'email': None, 'phone': ...",10,False,Exhibition designer,False,False
35,303,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-28,1,0,...,37.562544,16.280573,0,[],"{'appointment': None, 'email': None, 'phone': ...",11,False,Exhibition designer,False,False
36,354,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-29,1,0,...,50.913043,16.962272,0,[],"{'appointment': None, 'email': None, 'phone': ...",12,False,Exhibition designer,False,False
37,409,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-30,1,0,...,46.344206,14.591492,0,[],"{'appointment': None, 'email': None, 'phone': ...",13,False,Exhibition designer,False,False
38,467,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-01-31,1,0,...,55.549143,13.644686,0,[],"{'appointment': None, 'email': None, 'phone': ...",14,False,Exhibition designer,False,False
39,529,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-01,1,0,...,43.054421,13.886320,0,[email],"{'appointment': None, 'email': None, 'phone': ...",15,False,Exhibition designer,False,False
40,595,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-02,1,0,...,48.493201,17.261047,0,[],"{'appointment': None, 'email': None, 'phone': ...",16,False,Exhibition designer,False,False
41,741,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-04,1,0,...,45.612803,14.692317,0,[],"{'appointment': None, 'email': None, 'phone': ...",18,False,Exhibition designer,False,False
42,820,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-05,1,0,...,47.829585,14.147516,0,[],"{'appointment': None, 'email': None, 'phone': ...",19,False,Exhibition designer,False,False
43,903,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-06,1,0,...,44.177534,14.427735,0,"[whatsapp, email, appointment]","{'appointment': None, 'email': None, 'phone': ...",20,False,Exhibition designer,False,False
44,990,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-07,1,0,...,50.886329,15.898074,0,[],"{'appointment': None, 'email': None, 'phone': ...",21,False,Exhibition designer,False,False
45,1082,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-08,1,0,...,45.940408,17.898837,0,[],"{'appointment': None, 'email': None, 'phone': ...",22,False,Exhibition designer,False,False
46,1177,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-09,1,0,...,46.672983,14.084331,0,[],"{'appointment': None, 'email': None, 'phone': ...",23,False,Exhibition designer,False,False
47,1275,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-10,1,0,...,47.797645,12.853597,0,[],"{'appointment': None, 'email': None, 'phone': ...",24,False,Exhibition designer,False,False
48,1374,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-11,1,0,...,47.840166,14.717018,0,[],"{'appointment': None, 'email': None, 'phone': ...",25,False,Exhibition designer,False,False
49,1475,2,3.5,Bonnie Carr,Greece,1947-05-27,00867 Dominguez Camp Apt. 575\nPort Josephland...,2008-02-12,1,0,...,47.298680,12.341826,0,"[whatsapp, email]","{'appointment': None, 'email': 7.0, 'phone': N...",26,False,Exhibition designer,False,False